name: stats
dependencies:
  -numpy=1.21.5
  -matplotlib=3.5.1
  -gspread=5.3.2
  -streamlit=1.9.0
  -seaborn=0.11.2
  -opencv-python=4.5.5.64
  -Pillow=9.1.0
  -dlib=19.23.1
  -scipy=1.4.1
  -pandas=1.3.5
  -imutils=0.5.4
