name: maskrcnn
channels:
  - conda-forge
  - defaults
dependencies:
  - dlib=19.23.1
  - cmake=3.22.4
  - cycler=0.11.0
  - cython=0.29.28
  - gitpython=3.1.27
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpcio=1.44.0
  - gspread=5.3.2
  - imutils=0.5.4
  - matplotlib=3.5.1
  - matplotlib-inline=0.1.3
  - numpy=1.21.5
  - oauthlib=3.2.0
  - opencv-python=4.5.5.64
  - openpyxl=3.0.9
  - pandas=1.3.5
  - pandocfilters=1.5.0
  - pickleshare=0.7.5
  - pillow=9.1.0
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - scipy==1.4.1
  - seaborn=0.11.2
  - urllib3=1.26.9
  - watchdog=2.1.7
  - wcwidth=0.2.5
  - werkzeug=2.1.1
