name: maskrcnn
channels:
  - conda-forge
  - defaults
dependencies:
  - dlib=19.23.1
  - gspread=5.3.2
  - imutils=0.5.4
  - matplotlib=3.5.1
  - numpy=1.21.5
  - opencv-python=4.5.5
  - openpyxl=3.0.9
  - pandas=1.3.5
  - pillow=9.1.0
  - scipy==1.4.1
  - seaborn=0.11.2
